' Example from https://plantuml.com/de/
@startuml
!include ../../assets/plantuml/puml-theme-rtd-light.puml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
note bottom: Representation of Time

annotation SuppressWarnings

TimeUnit -[hidden]-> SuppressWarnings
@enduml
