name: Documentation

# **What it does**:
# Provides all tools to run our Sphinx Documentation Template.
# Further can host the documentation on a webserver.
# **Why we have it**:
# To build the documentation having the right version of tools.
# Especially, the plantuml version is important for adding the
# custom RTD theme.
# **Who does it impact**: None

run-name: Build and deploy documentation from ${{ github.sha }}
on:
  push:
    branches:
      - main
      - fix-*
  workflow_run:
    workflows: [Build Docker image]
    types: [completed]
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sphinx-gx
  IMAGE_TAG: latest
  DOCS_INPUT_PATH: /sphinx-doc/docs
  DOCS_OUTPUT_PATH: /sphinx-doc/_build
jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    timeout-minutes: 15
    environment:
      name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
    # make sure to have docker 18.09+ installed
    steps:
      -
        name: Install bash
        shell: sh
        run: apk add bash
      -
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        name: Archive html docs
        uses: actions/upload-artifact@v3
        with:
          name: ARDSL_Documentation
          path: ${GITHUB_WORKSPACE}/_build
          # optionally exclude all puml, structurizr dsl and mermaid files
          # before excluding mermaid files, make sure to have build them using the mermaid cli to svgs

  # Execute Linkchecker
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest

  # Deploy as GH Page
  deploy-gh-page:
    needs: build-docs
    runs-on: ubuntu:22-04
    steps:
      -
        name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: ARDSL_Documentation
      -
        name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_build'
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
