name: sphinx
run-name: Build Docker image for extended sphinx
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**/*'
      - 'docs/requirements.txt'
      - 'docs/conf.py'

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: # docker run -d -it --name=sphinx_c -v "$(if [[ "$OSTYPE" == "msys" ]]; then cygpath -w `pwd`; else pwd; fi)"/docs:/data sphinx-template:v0.1.0
        shell: bash 
