name: Sphinx-GX

# **What it does**:
# If the docker setup changes, it rebuilds the image and pushes it to our registry.
# **Why we have it**:
# To reduce the build times of the pipeline to build documentations
# **Who does it impact**:
# The docker image must be provided for the docs.yml workflow

run-name: Build sphinx image from Commit ${{ github.sha }}
on:
  push:
    branches:
      - main
      - fix/*-ghx-*
    paths:
      - 'docker/**'

env:
  REGISTRY: ghcr.io
  # abbrev. for sphinx-graphical-actions
  IMAGE_NAME: sphinx-gx
  IMAGE_TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 15
    steps:
      -
        name: Break
        shell: sh
        run: exit 1
      -
        name: Checkout Repository
        uses: actions/checkout@v3
      -
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          # todo update login information
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
